"""Add name field to nfc_cards table

Revision ID: 10ce4f72617b
Revises: 0b746c66e14e
Create Date: 2025-10-16 14:24:01.218764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ce4f72617b'
down_revision: Union[str, Sequence[str], None] = '0b746c66e14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nfc_cards_uid'), table_name='nfc_cards')
    op.drop_table('nfc_cards')
    op.drop_index(op.f('ix_vault_invitations_invite_code'), table_name='vault_invitations')
    op.drop_table('vault_invitations')
    op.drop_index(op.f('ix_vault_memberships_user_id'), table_name='vault_memberships')
    op.drop_index(op.f('ix_vault_memberships_vault_id'), table_name='vault_memberships')
    op.drop_table('vault_memberships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vault_id', name=op.f('uq_vault_membership_user_vault'))
    )
    op.create_index(op.f('ix_vault_memberships_vault_id'), 'vault_memberships', ['vault_id'], unique=False)
    op.create_index(op.f('ix_vault_memberships_user_id'), 'vault_memberships', ['user_id'], unique=False)
    op.create_table('vault_invitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.INTEGER(), nullable=False),
    sa.Column('invited_by', sa.INTEGER(), nullable=False),
    sa.Column('invite_code', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code', name=op.f('uq_vault_invitation_code'))
    )
    op.create_index(op.f('ix_vault_invitations_invite_code'), 'vault_invitations', ['invite_code'], unique=1)
    op.create_table('nfc_cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfc_cards_uid'), 'nfc_cards', ['uid'], unique=1)
    # ### end Alembic commands ###
