"""add_new_owner_user_id_to_vault_invitations

Revision ID: 2a21ce4b2f2a
Revises: bc512ffed74b
Create Date: 2025-11-03 22:01:07.506357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a21ce4b2f2a'
down_revision: Union[str, Sequence[str], None] = 'bc512ffed74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_invitations') as batch_op:
        batch_op.add_column(sa.Column('new_owner_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vault_invitations_new_owner_user_id', 'users', ['new_owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_invitations') as batch_op:
        batch_op.drop_constraint('fk_vault_invitations_new_owner_user_id', type_='foreignkey')
        batch_op.drop_column('new_owner_user_id')
    # ### end Alembic commands ###
