"""add_non_admin_users_table

Revision ID: 30e23962be15
Revises: 65d8e0f60e29
Create Date: 2025-10-02 20:40:21.849917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e23962be15'
down_revision: Union[str, Sequence[str], None] = '65d8e0f60e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_admin_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('nfc_card_id', sa.INTEGER(), nullable=True),
    sa.Column('keypad_pin_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['nfc_card_id'], ['nfc_cards.id'], ),
    sa.ForeignKeyConstraint(['keypad_pin_id'], ['keypad_pins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('non_admin_users')
    # ### end Alembic commands ###
