"""Rename nfc_uid to pin_code in KeypadPins

Revision ID: 413802f8c8cf
Revises: 
Create Date: 2025-09-12 04:12:07.334804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '413802f8c8cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column to preserve data using batch alter
    with op.batch_alter_table('keypad_pins') as batch_op:
        batch_op.alter_column('nfc_uid', new_column_name='pin_code')
    # Create new index
    op.create_index(op.f('ix_keypad_pins_pin_code'), 'keypad_pins', ['pin_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column back using batch alter
    with op.batch_alter_table('keypad_pins') as batch_op:
        batch_op.alter_column('pin_code', new_column_name='nfc_uid')
    # Create old index
    op.create_index(op.f('ix_keypad_pins_nfc_uid'), 'keypad_pins', ['nfc_uid'], unique=True)
    # ### end Alembic commands ###
