"""add_vault_membership_table

Revision ID: 43d83a0ddf6e
Revises: f790dc8dfa1c
Create Date: 2025-10-03 00:55:57.454518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d83a0ddf6e'
down_revision: Union[str, Sequence[str], None] = 'f790dc8dfa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the vault_memberships table
    op.create_table('vault_memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vault_id', name='uq_vault_membership_user_vault')
    )
    op.create_index(op.f('ix_vault_memberships_user_id'), 'vault_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_vault_memberships_vault_id'), 'vault_memberships', ['vault_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the vault_memberships table
    op.drop_index(op.f('ix_vault_memberships_vault_id'), table_name='vault_memberships')
    op.drop_index(op.f('ix_vault_memberships_user_id'), table_name='vault_memberships')
    op.drop_table('vault_memberships')

    # ### end Alembic commands ###
