"""Add updated_at to vault_invitations

Revision ID: 5aa1bafe3dc2
Revises: 79f90b279d8d
Create Date: 2025-11-05 17:01:40.365665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa1bafe3dc2'
down_revision: Union[str, Sequence[str], None] = '79f90b279d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('logs', 'event_type',
    #            existing_type=sa.VARCHAR(length=17),
    #            type_=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', 'unlock_confirm', 'ownership_transfer_initiated', 'ownership_transfer_accepted', name='logeventtype'),
    #            existing_nullable=False)
    op.add_column('vault_invitations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('vault_invitations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_invitations', 'deleted_at')
    op.drop_column('vault_invitations', 'updated_at')
    # op.alter_column('logs', 'event_type',
    #            existing_type=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', 'unlock_confirm', 'ownership_transfer_initiated', 'ownership_transfer_accepted', name='logeventtype'),
    #            type_=sa.VARCHAR(length=17),
    #            existing_nullable=False)
    # ### end Alembic commands ###
