"""Add first_name and last_name to users table

Revision ID: 65d8e0f60e29
Revises: 413802f8c8cf
Create Date: 2025-09-18 02:44:44.400639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d8e0f60e29'
down_revision: Union[str, Sequence[str], None] = '413802f8c8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping unrelated changes to focus on adding first_name and last_name
    # Add columns as nullable with default empty string
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True, server_default=""))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # Skipping unrelated changes
    # ### end Alembic commands ###
