"""add_ownership_transfer_log_event_types

Revision ID: 79f90b279d8d
Revises: 2a21ce4b2f2a
Create Date: 2025-11-03 22:28:57.154164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f90b279d8d'
down_revision: Union[str, Sequence[str], None] = '2a21ce4b2f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('logs', 'event_type',
    #            existing_type=sa.VARCHAR(length=17),
    #            type_=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', 'unlock_confirm', 'ownership_transfer_initiated', 'ownership_transfer_accepted', name='logeventtype'),
    #            existing_nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('logs', 'event_type',
    #            existing_type=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', 'unlock_confirm', 'ownership_transfer_initiated', 'ownership_transfer_accepted', name='logeventtype'),
    #            type_=sa.VARCHAR(length=17),
    #            existing_nullable=False)
    pass
    # ### end Alembic commands ###
