"""add_first_name_last_name_to_users

Revision ID: 86eea0cb5deb
Revises: 6d2e4c802c40
Create Date: 2025-10-04 04:48:17.251481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eea0cb5deb'
down_revision: Union[str, Sequence[str], None] = '6d2e4c802c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_memberships')
    op.drop_table('user_vaults')
    op.drop_index(op.f('ix_nfc_cards_uid'), table_name='nfc_cards')
    op.drop_table('nfc_cards')
    op.drop_index(op.f('ix_vault_invitations_invite_code'), table_name='vault_invitations')
    op.drop_table('vault_invitations')
    op.alter_column('logs', 'event_type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', name='logeventtype'),
               existing_nullable=False)
    op.drop_column('logs', 'timestamp')
    op.alter_column('vaults', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'vaults', ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaults', type_='unique')
    op.alter_column('vaults', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('logs', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.alter_column('logs', 'event_type',
               existing_type=sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', name='logeventtype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.create_table('vault_invitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.VARCHAR(), nullable=False),
    sa.Column('invited_by', sa.INTEGER(), nullable=False),
    sa.Column('invite_code', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code', name=op.f('uq_vault_invitation_code'))
    )
    op.create_index(op.f('ix_vault_invitations_invite_code'), 'vault_invitations', ['invite_code'], unique=1)
    op.create_table('nfc_cards',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfc_cards_uid'), 'nfc_cards', ['uid'], unique=1)
    op.create_table('user_vaults',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('vault_id', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vault_id', name=op.f('uq_vault_membership_user_vault'))
    )
    # ### end Alembic commands ###
