"""add_first_name_last_name_to_users

Revision ID: 86eea0cb5deb
Revises: 6d2e4c802c40
Create Date: 2025-10-04 04:48:17.251481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eea0cb5deb'
down_revision: Union[str, Sequence[str], None] = '6d2e4c802c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Only drop tables if they exist
    try:
        op.drop_table('vault_memberships')
    except Exception:
        pass  # Table doesn't exist, skip

    try:
        op.drop_table('user_vaults')
    except Exception:
        pass  # Table doesn't exist, skip

    # Drop existing indexes and tables that should exist (defensive approach)
    try:
        op.drop_index(op.f('ix_nfc_cards_uid'), table_name='nfc_cards')
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_table('nfc_cards')
    except Exception:
        pass  # Table might not exist

    try:
        op.drop_index(op.f('ix_vault_invitations_invite_code'), table_name='vault_invitations')
    except Exception:
        pass  # Index might not exist

    try:
        op.drop_table('vault_invitations')
    except Exception:
        pass  # Table might not exist

    # Update vaults table - SQLite compatible approach using batch operations
    with op.batch_alter_table('vaults') as batch_op:
        # Add new column with correct constraints (with default value)
        batch_op.add_column(sa.Column('device_id_new', sa.VARCHAR(), nullable=False, server_default=''))

        # Copy data from old column to new column
        op.execute("UPDATE vaults SET device_id_new = device_id WHERE device_id IS NOT NULL")

        # Drop old column and rename new column
        batch_op.drop_column('device_id')
        batch_op.alter_column('device_id_new', new_column_name='device_id')

        # Create unique constraint
        batch_op.create_unique_constraint('uq_vaults_device_id', ['device_id'])

    # Update logs table - SQLite compatible approach
    # Check if event_type_new already exists (from partial migration)
    try:
        # If event_type_new exists, just rename it
        op.drop_column('logs', 'event_type')
        op.alter_column('logs', 'event_type_new', new_column_name='event_type')
    except Exception:
        # If event_type_new doesn't exist, do the full conversion
        op.add_column('logs', sa.Column('event_type_new',
                   sa.Enum('unlock', 'lock', 'failed_attempt', 'tamper', 'alarm', 'disconnected', 'need_other_factor', 'access_granted', 'connected', name='logeventtype'),
                   nullable=False, server_default='unlock'))
        op.execute("UPDATE logs SET event_type_new = event_type")
        op.drop_column('logs', 'event_type')
        op.alter_column('logs', 'event_type_new', new_column_name='event_type')

    # Drop timestamp column if it exists
    try:
        op.drop_column('logs', 'timestamp')
    except Exception:
        pass  # Column might not exist

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the vaults table changes using batch operations
    with op.batch_alter_table('vaults') as batch_op:
        # Drop unique constraint
        batch_op.drop_constraint('uq_vaults_device_id', type_='unique')

        # Convert back to nullable - SQLite compatible approach
        batch_op.add_column(sa.Column('device_id_old', sa.VARCHAR(), nullable=True, server_default=''))
        op.execute("UPDATE vaults SET device_id_old = device_id")
        batch_op.drop_column('device_id')
        batch_op.alter_column('device_id_old', new_column_name='device_id')
    # Add timestamp column if it doesn't exist
    try:
        op.add_column('logs', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    except Exception:
        pass  # Column might already exist

    # Convert enum back to VARCHAR for SQLite compatibility
    op.add_column('logs', sa.Column('event_type_old', sa.VARCHAR(length=14), nullable=False))

    # Copy data and convert back
    op.execute("UPDATE logs SET event_type_old = event_type")

    # Drop enum column and rename VARCHAR column
    op.drop_column('logs', 'event_type')
    op.alter_column('logs', 'event_type_old', new_column_name='event_type')

    # Recreate tables (only if they don't exist)
    try:
        op.create_table('vault_invitations',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('vault_id', sa.VARCHAR(), nullable=False),
        sa.Column('invited_by', sa.INTEGER(), nullable=False),
        sa.Column('invite_code', sa.VARCHAR(), nullable=False),
        sa.Column('role', sa.VARCHAR(length=6), nullable=False),
        sa.Column('expires_at', sa.DATETIME(), nullable=False),
        sa.Column('accepted', sa.BOOLEAN(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('invite_code', name=op.f('uq_vault_invitation_code'))
        )
        op.create_index(op.f('ix_vault_invitations_invite_code'), 'vault_invitations', ['invite_code'], unique=1)
    except Exception:
        pass  # Table might already exist

    try:
        op.create_table('nfc_cards',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=False),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.Column('deleted_at', sa.DATETIME(), nullable=True),
        sa.Column('uid', sa.VARCHAR(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_nfc_cards_uid'), 'nfc_cards', ['uid'], unique=1)
    except Exception:
        pass  # Table might already exist

    # Only create these tables if they don't exist
    try:
        op.create_table('user_vaults',
        sa.Column('id', sa.VARCHAR(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=False),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.Column('deleted_at', sa.DATETIME(), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('vault_id', sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    except Exception:
        pass  # Table might already exist

    try:
        op.create_table('vault_memberships',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('vault_id', sa.VARCHAR(), nullable=False),
        sa.Column('role', sa.VARCHAR(length=6), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=False),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'vault_id', name=op.f('uq_vault_membership_user_vault'))
        )
    except Exception:
        pass  # Table might already exist

    # ### end Alembic commands ###
