"""add_ownership_transfer_fields_to_vault_invitation

Revision ID: bc512ffed74b
Revises: 3ad2df5a50f8
Create Date: 2025-11-03 20:44:35.778266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc512ffed74b'
down_revision: Union[str, Sequence[str], None] = '3ad2df5a50f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_invitations', sa.Column('is_ownership_transfer', sa.Boolean(), nullable=False))
    op.add_column('vault_invitations', sa.Column('transfer_type', sa.Enum('full_transfer', 'shared_access', name='transfertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_invitations', 'transfer_type')
    op.drop_column('vault_invitations', 'is_ownership_transfer')
    # ### end Alembic commands ###
